# Imports

In [1]:
import os
import pandas as pd
from collections import Counter

# Prepare NaijaVoices dataset

In [2]:
train_path = "../naijavoices/train.csv"
dev_path = "../naijavoices/dev.csv"
test_path = "../naijavoices/test.csv"

train_df = pd.read_csv(train_path)
dev_df = pd.read_csv(dev_path)
test_df = pd.read_csv(test_path)

In [3]:
# get Igbo subset
train_df = train_df[train_df['language'] == 'igbo']
dev_df = dev_df[dev_df['language'] == 'igbo']
test_df = test_df[test_df['language'] == 'igbo']

# drop language column
train_df = train_df.drop(columns=['language'])
dev_df = dev_df.drop(columns=['language'])
test_df = test_df.drop(columns=['language'])

In [4]:
train_df.describe(include="all")

,speaker_id,audio,text,age_bracket,gender,phase,exists,duration,snr
count,617674,617674,617674,617674,617674,617674,617674.0,617645.000000,617616.000000
unique,1802,577754,214829,3,2,2,NaN,NaN,NaN
top,02EVM,20240112110547-18-165-35966-nwanne-nna-m-nke-n...,Kedụ ihe ị mụtara n'akụkọ mbe na nwunye ya?,18-29,female,phase 1,NaN,NaN,NaN
freq,19382,81,92,442949,356309,453268,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.894608,84.757141
std,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.708912,26.687497
min,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.060000,-20.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.760000,73.713852
50%,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.540000,100.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,1.0,4.620000,100.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,1.0,206.280000,100.000000

In [5]:
dev_df.describe(include="all")

,speaker_id,audio,text,age_bracket,gender,phase,exists,duration,snr
count,929,929,929,929,929,929,929.0,929.000000,929.000000
unique,582,929,928,3,2,2,NaN,NaN,NaN
top,02EVM,20240426155834-49-2754-701096-mba-nna-m-ukwu-a...,Ahụrụ m ndị nche ụlọ akwụkwọ anyị n'ụzọ.,18-29,female,phase 1,NaN,NaN,NaN
freq,27,1,2,667,536,688,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.869774,83.500105
std,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.650553,27.769534
min,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.780000,7.829210
25%,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.760000,64.318792
50%,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.540000,100.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,1.0,4.680000,100.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,1.0,13.980000,100.000000

In [6]:
test_df.describe(include="all")

,speaker_id,audio,text,age_bracket,gender,phase,exists,duration,snr
count,1018,1018,1018,1018,1018,1018,1018.0,1018.000000,1018.000000
unique,583,1014,1013,3,2,2,NaN,NaN,NaN
top,02EVM,20240112075223-18-165-35785-otu-n-ime-uru-icha...,Otu n'ime uru ịcha ntutu gị bụ na ọ na-eme ka ...,18-29,female,phase 1,NaN,NaN,NaN
freq,31,2,2,672,597,777,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.913851,86.308361
std,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.697084,25.646932
min,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.960000,13.261869
25%,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.760000,100.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.540000,100.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,1.0,4.725000,100.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,1.0,13.560000,100.000000

In [7]:
# check for missing values
train_df.isnull().sum()

speaker_id      0
audio           0
text            0
age_bracket     0
gender          0
phase           0
exists          0
duration       29
snr            58
dtype: int64

In [8]:
# drop rows with missing values in 'duration' column
train_df = train_df.dropna(subset=['duration'])

In [9]:
dev_df.isnull().sum()

speaker_id     0
audio          0
text           0
age_bracket    0
gender         0
phase          0
exists         0
duration       0
snr            0
dtype: int64

In [10]:
test_df.isnull().sum()

speaker_id     0
audio          0
text           0
age_bracket    0
gender         0
phase          0
exists         0
duration       0
snr            0
dtype: int64

In [11]:
# drop unnecessary columns
drop_cols = ['phase', 'exists', 'snr', 'speaker_id']
train_df.drop(columns=drop_cols + ['gender', 'age_bracket'], inplace=True)
dev_df.drop(columns=drop_cols + ['gender', 'age_bracket'], inplace=True)
test_df.drop(columns=drop_cols, inplace=True)

In [12]:
# find duplicates
train_df[train_df.duplicated(subset='audio')].sort_values(by='audio').head(10)

,audio,text,duration
1970090,20231205142202-19-10-1615--ga-azta-abada-na-ch...,Ị ga-azụta abada na ịchafụ?,2.16
1660217,20231205142202-19-10-1615--ga-azta-abada-na-ch...,Ị ga-azụta abada na ịchafụ?,2.16
1833377,20231205142202-19-10-1615--ga-azta-abada-na-ch...,Ị ga-azụta abada na ịchafụ?,2.16
1261735,20231206111045-19-11-1681-aunty-ngozi-na-arsi-...,Aunty Ngozi na-arụsi ọrụ ike,2.88
1583191,20231206111045-19-11-1681-aunty-ngozi-na-arsi-...,Aunty Ngozi na-arụsi ọrụ ike,2.88
1354225,20231206111045-19-11-1681-aunty-ngozi-na-arsi-...,Aunty Ngozi na-arụsi ọrụ ike,2.88
2058788,20231206111129-19-11-1682-eji-m-mkpr-k-a-gbar.wav,Eji m mkpụrụ ọkà a gbara na mkpọ bịa.,3.60
1044826,20231206111129-19-11-1682-eji-m-mkpr-k-a-gbar.wav,Eji m mkpụrụ ọkà a gbara na mkpọ bịa.,3.60
369100,20231206111129-19-11-1682-eji-m-mkpr-k-a-gbar.wav,Eji m mkpụrụ ọkà a gbara na mkpọ bịa.,3.60
184482,20231206111400-19-11-1685-csn-b-nwa-nwanne-nne...,Cụsịn bụ nwa nwanne nne ma ọ bụ nna.,3.96

In [13]:
dev_df[dev_df.duplicated(subset='audio')].sort_values(by='audio')

Empty DataFrame
Columns: [audio, text, duration]
Index: []

In [14]:
test_df[test_df.duplicated(subset='audio')].sort_values(by='audio')

,audio,text,age_bracket,gender,duration
562,20240112075223-18-165-35785-otu-n-ime-uru-icha...,Otu n'ime uru ịcha ntutu gị bụ na ọ na-eme ka ...,6-17,male,3.66
1248,20240112084624-18-165-35762-ulo-otutu-ezinulo-...,Ụlọ ọtụtụ ezinụlọ bụ ụlọ na-anabata ọtụtụ ezin...,6-17,male,4.98
2112,20240112102238-18-165-35911-ihe-ruru-nde-iri-i...,Ihe ruru nde iri iteghete soro ọgụ egwu Rihann...,6-17,male,5.34
1724,20240112111608-18-165-35986-o-ga-aga-scanu-n-o...,Ọ ga-aga scanụ n'ọnwa isii ya,6-17,male,2.52

In [15]:
# drop duplicates
train_df = train_df.drop_duplicates(subset='audio')
dev_df = dev_df.drop_duplicates(subset='audio')
test_df = test_df.drop_duplicates(subset='audio')

In [16]:
# get the audio file paths
path = '../naijavoices/'

train_df['audio_filepath'] = train_df['audio'].apply(lambda x: os.path.join(os.path.dirname(path), "audio-unconverted", x))
dev_df['audio_filepath'] = dev_df['audio'].apply(lambda x: os.path.join(os.path.dirname(path), "audio-unconverted", x))
test_df['audio_filepath'] = test_df['audio'].apply(lambda x: os.path.join(os.path.dirname(path), "audio-unconverted", x))

# drop the `audio` column
train_df.drop(columns=['audio'], inplace=True)
dev_df.drop(columns=['audio'], inplace=True)
test_df.drop(columns=['audio'], inplace=True)

In [17]:
train_df.describe(include="all")

,text,duration,audio_filepath
count,577725,577725.000000,577725
unique,214819,NaN,577725
top,Nna bụ onyeisi ezinụlọ.,NaN,../naijavoices/audio-unconverted/2024010414201...
freq,18,NaN,1
mean,NaN,3.890556,NaN
std,NaN,1.713058,NaN
min,NaN,0.060000,NaN
25%,NaN,2.760000,NaN
50%,NaN,3.540000,NaN
75%,NaN,4.620000,NaN
max,NaN,206.280000,NaN

In [18]:
dev_df.describe(include="all")

,text,duration,audio_filepath
count,929,929.000000,929
unique,928,NaN,929
top,Ahụrụ m ndị nche ụlọ akwụkwọ anyị n'ụzọ.,NaN,../naijavoices/audio-unconverted/2024042615583...
freq,2,NaN,1
mean,NaN,3.869774,NaN
std,NaN,1.650553,NaN
min,NaN,0.780000,NaN
25%,NaN,2.760000,NaN
50%,NaN,3.540000,NaN
75%,NaN,4.680000,NaN
max,NaN,13.980000,NaN

In [19]:
test_df.describe(include="all")

,text,age_bracket,gender,duration,audio_filepath
count,1014,1014,1014,1014.000000,1014
unique,1013,3,2,NaN,1014
top,Ebube tara unere na ahụ ékẹrè.,18-29,female,NaN,../naijavoices/audio-unconverted/2023122616491...
freq,2,672,597,NaN,1
mean,NaN,NaN,NaN,3.913018,NaN
std,NaN,NaN,NaN,1.698928,NaN
min,NaN,NaN,NaN,0.960000,NaN
25%,NaN,NaN,NaN,2.760000,NaN
50%,NaN,NaN,NaN,3.540000,NaN
75%,NaN,NaN,NaN,4.680000,NaN
max,NaN,NaN,NaN,13.560000,NaN

In [20]:
# remove long audio files from train and dev sets
train_df = train_df[train_df['duration'] <= 15]
dev_df = dev_df[dev_df['duration'] <= 15]
print(f"Total training set duration: {train_df['duration'].sum() / 3600:.2f} hours")

Total training set duration: 622.59 hours

In [21]:
train_df.head()

,text,duration,audio_filepath
3,Dike ga-asacha agwa ọ ga-etinye na makaroni.,3.12,../naijavoices/audio-unconverted/2024032009035...
5,Mekaniiki ahụ ka na-arụ otu ụgbọala ahụ kemgbe...,3.90,../naijavoices/audio-unconverted/2024011210475...
6,Eze mmiri ara m dapụrụ ụnyaahụ,2.40,../naijavoices/audio-unconverted/2024020314031...
8,Eke juru n'ọhịa enweghi otu ụdị.,3.24,../naijavoices/audio-unconverted/2023122000592...
14,Munye ọkụ ahụ echi!,1.86,../naijavoices/audio-unconverted/2024011209025...

In [22]:
# save original text before cleaning
train_df['original_text'] = train_df['text']
dev_df['original_text'] = dev_df['text']
test_df['original_text'] = test_df['text']

In [23]:
# lowercase the text
train_df['text'] = train_df['text'].str.lower()
dev_df['text'] = dev_df['text'].str.lower()
test_df['text'] = test_df['text'].str.lower()

# get the set of characters in the text
train_text = "".join(train_df['text'].tolist())
dev_text = "".join(dev_df['text'].tolist())
text = train_text + dev_text

set(text)

{'\t',
 '\n',
 ' ',
 '!',
 '"',
 '#',
 '$',
 '&',
 "'",
 '(',
 ')',
 '*',
 '+',
 ',',
 '-',
 '.',
 '/',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '?',
 '\\',
 ']',
 '_',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '\xa0',
 '´',
 '·',
 'à',
 'á',
 'â',
 'è',
 'é',
 'ê',
 'ë',
 'ì',
 'í',
 'î',
 'ï',
 'ñ',
 'ò',
 'ó',
 'ô',
 'ö',
 'ù',
 'ú',
 'û',
 'ü',
 'ā',
 'ē',
 'ė',
 'ī',
 'ı',
 'ń',
 'ō',
 'ő',
 'œ',
 'ū',
 'ų',
 'ƴ',
 'ǃ',
 'ǹ',
 'ɑ',
 'ɛ',
 'ɨ',
 'ʉ',
 'ʻ',
 'ː',
 '̀',
 '́',
 '̄',
 '̇',
 '̌',
 '̜',
 '̣',
 '̧',
 '̻',
 '̼',
 '͈',
 '͕',
 'μ',
 '᷂',
 'ḅ',
 'ḿ',
 'ṅ',
 'ṇ',
 'ṛ',
 'ṣ',
 'ạ',
 'ẹ',
 'ị',
 'ọ',
 'ụ',
 'ự',
 '\u200b',
 '–',
 '‘',
 '’',
 '“',
 '”',
 '⁰',
 '₦'}

In [24]:
char = '\u200b'

# find rows with the character
train_df[train_df['text'].str.contains(char)]

,text,duration,audio_filepath,original_text
9884,agadi onye ọrụ ugbo kwuru amamihe ya site n’il...,6.06,../naijavoices/audio-unconverted/2024032215512...,Agadi onye ọrụ ugbo kwuru amamihe ya site n’il...
17973,ị nọ na ụka ​​taa?,2.58,../naijavoices/audio-unconverted/2023123007181...,Ị nọ na Ụka ​​taa?
32260,"mba, echefughị ​​m akpa m n'ebe a na-ere ahịa",4.74,../naijavoices/audio-unconverted/2024011512251...,"Mba, echefughị ​​m akpa m n'ebe a na-ere ahịa"
45303,à ga-akpọlite ​​ndị nwụrụ anwụ n'ọnwụ?,3.30,../naijavoices/audio-unconverted/2024032514330...,À ga-akpọlite ​​ndị nwụrụ anwụ n'ọnwụ?
74556,anọ m na ụka ​​taa.,1.74,../naijavoices/audio-unconverted/2024032214051...,Anọ m na Ụka ​​taa.
...,...,...,...,...
2012296,"iji nwetakwuo njide onwe onye, ​​ịkwesịrị ịchị...",4.38,../naijavoices/audio-unconverted/2024012817011...,"Iji nwetakwuo njide onwe onye, ​​ịkwesịrị ịchị..."
2045469,onye ode akwụkwọ ụlọikpe ahụ gwara onye ọ bụla...,7.62,../naijavoices/audio-unconverted/2024010722260...,Onye ode akwụkwọ ụlọikpe ahụ gwara onye ọ bụla...
2049514,aha dịka ụka ​​baptist na methodist church bụ ...,6.96,../naijavoices/audio-unconverted/2024012913003...,Aha dịka Ụka ​​Baptist na Methodist Church bụ ...
2060771,ànyị kwesịrị ịkwụsị ikwu okwu n’ilu ​​echi?,3.30,../naijavoices/audio-unconverted/2023121907192...,Ànyị kwesịrị ịkwụsị ikwu okwu n’ilu ​​echi?
2085851,"maazị okoro sịrị, apụtakwala iro ụbọchị​ eke",5.16,../naijavoices/audio-unconverted/2023122214294...,"Maazị Okoro sịrị, apụtakwala iro ụbọchị​ Eke"

In [25]:
print(f"'{char}'")

'​'

In [26]:
# remove punctuation and special characters
CHARS_TO_REMOVE = ['"', '!', 'ǃ', '(', ')', ',', '.', ':', ';', '?', '[', ']', '\u200b']

for char in CHARS_TO_REMOVE:
    train_df['text'] = train_df['text'].str.replace(char, '', regex=False)
    dev_df['text'] = dev_df['text'].str.replace(char, '', regex=False)
    test_df['text'] = test_df['text'].str.replace(char, '', regex=False)

# replace whitespace characters with a single space
WHITESPACE_CHARS = ['\xa0', '\t', '/']
for char in WHITESPACE_CHARS:
    train_df['text'] = train_df['text'].str.replace(char, ' ', regex=False)
    dev_df['text'] = dev_df['text'].str.replace(char, ' ', regex=False)
    test_df['text'] = test_df['text'].str.replace(char, ' ', regex=False)

# strip leading and trailing whitespace from the text column
train_df['text'] = train_df['text'].str.strip()
dev_df['text'] = dev_df['text'].str.strip()
test_df['text'] = test_df['text'].str.strip()

# remove excess whitespace
train_df['text'] = train_df['text'].str.replace(r'\s+', ' ', regex=True)
dev_df['text'] = dev_df['text'].str.replace(r'\s+', ' ', regex=True)
test_df['text'] = test_df['text'].str.replace(r'\s+', ' ', regex=True)

In [27]:
# get the frequency of each character in the train and dev sets
char_freq = Counter(text)
char_freq

Counter({' ': 4233704,
         'a': 3090924,
         'e': 1731443,
         'n': 1662952,
         'ụ': 1158324,
         'i': 1148339,
         'k': 860339,
         'ọ': 837952,
         'm': 818185,
         'g': 731582,
         'r': 728042,
         'ị': 685358,
         'h': 641385,
         'o': 634026,
         'w': 581472,
         'b': 579391,
         'u': 571845,
         't': 443055,
         'd': 397050,
         'y': 359745,
         'l': 336802,
         's': 326097,
         '-': 275691,
         '.': 267750,
         'p': 219343,
         'c': 215322,
         "'": 172596,
         'z': 164492,
         'j': 148918,
         'f': 90731,
         ',': 90457,
         '?': 75175,
         '!': 31302,
         '̣': 24662,
         'á': 20812,
         'ṅ': 17450,
         'à': 15783,
         'v': 14437,
         'é': 14003,
         'è': 10216,
         'í': 7195,
         '"': 7009,
         'ú': 6613,
         '’': 6415,
         'ù': 6172,
         '̀': 5686,
         '́': 5066,
         'ó': 3876,
         'ì': 3602,
         'ò': 3197,
         'ñ': 1074,
         'x': 997,
         '2': 817,
         'q': 768,
         '1': 746,
         '0': 673,
         '9': 576,
         '̄': 545,
         'ń': 372,
         'ǃ': 332,
         '\xa0': 331,
         '4': 326,
         ':': 308,
         '3': 284,
         '\u200b': 274,
         'ẹ': 265,
         ')': 244,
         '(': 231,
         ';': 211,
         '5': 185,
         '6': 182,
         '/': 174,
         'ē': 151,
         '8': 149,
         'ǹ': 135,
         'ạ': 121,
         'ā': 107,
         '7': 95,
         '̇': 93,
         'ḿ': 52,
         'ų': 48,
         '”': 40,
         '͕': 37,
         '“': 35,
         'ô': 35,
         'ū': 35,
         'ï': 28,
         '‘': 27,
         '\n': 26,
         '_': 25,
         '#': 24,
         '&': 22,
         'ė': 20,
         '*': 19,
         'ü': 18,
         'â': 17,
         'ː': 17,
         'ō': 14,
         '+': 13,
         '̼': 12,
         '´': 11,
         '̻': 11,
         'ī': 9,
         'ê': 9,
         '̧': 8,
         'ɨ': 8,
         'û': 7,
         ']': 6,
         'ʻ': 6,
         '–': 6,
         'œ': 5,
         '$': 5,
         '\t': 4,
         '\\': 4,
         'î': 4,
         'ṣ': 4,
         '̜': 3,
         '᷂': 3,
         'ṇ': 3,
         '͈': 3,
         'ự': 3,
         '₦': 3,
         'ö': 3,
         'ë': 3,
         'ɑ': 3,
         '⁰': 3,
         'ő': 2,
         '·': 2,
         'ʉ': 2,
         'ı': 2,
         'ṛ': 2,
         'μ': 2,
         '̌': 2,
         'ƴ': 2,
         'ḅ': 2,
         'ɛ': 1})

In [28]:
# remove rows with infrequent characters from train and dev sets
min_freq = 95
train_df = train_df[train_df['text'].apply(lambda x: all(char_freq[c] >= min_freq for c in x))]
dev_df = dev_df[dev_df['text'].apply(lambda x: all(char_freq[c] >= min_freq for c in x))]

In [29]:
# recalculate character frequency after cleaning
train_text = "".join(train_df['text'].tolist())
dev_text = "".join(dev_df['text'].tolist())
text = train_text + dev_text

# get the frequency of each character in the train and dev sets
char_freq = Counter(text)
char_freq

Counter({' ': 4219702,
         'a': 3087207,
         'e': 1729495,
         'n': 1660864,
         'ụ': 1157242,
         'i': 1146785,
         'k': 859312,
         'ọ': 837228,
         'm': 817211,
         'g': 730738,
         'r': 727098,
         'ị': 684655,
         'h': 640579,
         'o': 632975,
         'w': 580797,
         'b': 578680,
         'u': 570889,
         't': 442449,
         'd': 396500,
         'y': 359262,
         'l': 336318,
         's': 325641,
         '-': 275391,
         'p': 219022,
         'c': 215037,
         "'": 172379,
         'z': 164256,
         'j': 148701,
         'f': 90654,
         '̣': 24203,
         'á': 20740,
         'ṅ': 17445,
         'à': 15731,
         'v': 14409,
         'é': 13936,
         'è': 10201,
         'í': 7120,
         'ú': 6594,
         '’': 6342,
         'ù': 6151,
         '̀': 5681,
         '́': 5054,
         'ó': 3833,
         'ì': 3594,
         'ò': 3167,
         'ñ': 1069,
         'x': 993,
         '2': 815,
         'q': 763,
         '1': 730,
         '0': 671,
         '̄': 545,
         '9': 543,
         'ń': 369,
         '4': 323,
         '3': 269,
         'ẹ': 265,
         '5': 182,
         '6': 182,
         '8': 149,
         'ē': 148,
         'ǹ': 135,
         'ạ': 121,
         '7': 95,
         'ā': 94})

In [30]:
# remove rows with anomalous character rates
train_df['character_rate'] = train_df['text'].str.len() / train_df['duration']
train_df['character_rate'].describe()

count    576709.000000
mean         11.038037
std           3.950689
min           0.282486
25%           9.340659
50%          10.964912
75%          12.601626
max        1600.000000
Name: character_rate, dtype: float64

In [31]:
dev_df['character_rate'] = dev_df['text'].str.len() / dev_df['duration']
dev_df['character_rate'].describe()

count    927.000000
mean      11.145375
std        2.503305
min        4.199475
25%        9.462240
50%       11.111111
75%       12.867965
max       19.166667
Name: character_rate, dtype: float64

In [32]:
MAX = 23
train_df = train_df[train_df['character_rate'] <= MAX]
dev_df = dev_df[dev_df['character_rate'] <= MAX]

train_df.drop(columns=['character_rate'], inplace=True)
dev_df.drop(columns=['character_rate'], inplace=True)

In [33]:
# save to NeMo jsonl format
train_manifest_path = os.path.join(os.path.dirname(path), "igbo_train_manifest.jsonl")
dev_manifest_path = os.path.join(os.path.dirname(path), "igbo_dev_manifest.jsonl")
test_manifest_path = os.path.join(os.path.dirname(path), "igbo_test_manifest.jsonl")

train_df.to_json(train_manifest_path, orient='records', lines=True)
dev_df.to_json(dev_manifest_path, orient='records', lines=True)
test_df.to_json(test_manifest_path, orient='records', lines=True)
print(f"Manifests saved to {path}")

Manifests saved to ../naijavoices/

# Sample

In [34]:
# get the total duration of each split
train_duration = train_df['duration'].sum()
dev_duration = dev_df['duration'].sum()
test_duration = test_df['duration'].sum()
print(f"Train duration: {train_duration / 3600:.2f} hours")
print(f"Dev duration: {dev_duration / 3600:.2f} hours")
print(f"Test duration: {test_duration / 3600:.2f} hours")

Train duration: 621.58 hours
Dev duration: 1.00 hours
Test duration: 1.10 hours

In [35]:
# rename the 'audio_filepath' column to 'audio'
train_df = train_df.rename(columns={'audio_filepath': 'audio'})
dev_df = dev_df.rename(columns={'audio_filepath': 'audio'})
test_df = test_df.rename(columns={'audio_filepath': 'audio'})

In [36]:
from datasets import Dataset, DatasetDict, Audio

dev = Dataset.from_pandas(dev_df)
test = Dataset.from_pandas(test_df)

/mnt/volume/workdir/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [37]:
# only keep necessary columns
cols = ['audio', 'text', 'duration']
dev = dev.remove_columns([col for col in dev.column_names if col not in cols])
test = test.remove_columns([col for col in test.column_names if col not in cols + ['gender', 'age_bracket']])

In [38]:
# cast audio column to Audio type
dev = dev.cast_column("audio", Audio(16000))
test = test.cast_column("audio", Audio(16000))

In [39]:
test[0]

{'text': "nwanyi ahụ si na ọbụ ọria obiri n'aja ọcha gbụrụ di ya",
 'age_bracket': '18-29',
 'gender': 'male',
 'duration': 4.26,
 'audio': <datasets.features._torchcodec.AudioDecoder at 0x778cef01f890>}

In [40]:
def sample_dataset(df, duration_minutes, manifest_name, random_state=1):
    """
    Sample a dataset to a specific duration.
    """
    total_duration = float(df['duration'].sum())
    ratio = (duration_minutes * 60) / total_duration
    n = int(len(df) * ratio)
    sample = df.sample(n=n, random_state=random_state)
    sample = sample.sample(frac=1, random_state=random_state).reset_index(drop=True)
    sample_duration = sample['duration'].sum()
    if sample_duration >= 3600:
        print(f"Sample duration: {sample_duration / 3600:.2f} hours")
    else:
        print(f"Sample duration: {sample_duration / 60:.2f} minutes")

    # save to new manifest
    sample_manifest_path = os.path.join(
        os.path.dirname(path),
        f"igbo_{manifest_name}_{int(sample_duration / 3600)}h.jsonl"
    )
    sample.to_json(sample_manifest_path, orient="records", lines=True)
    print(f"Manifest saved to {sample_manifest_path}")

    dataset = Dataset.from_pandas(sample)
    dataset = dataset.remove_columns([col for col in dataset.column_names if col not in cols])
    dataset = dataset.cast_column("audio", Audio(16000))
    return dataset

In [41]:
train = sample_dataset(train_df, 500 * 60, "train_manifest", random_state=10)

# save to disk
dataset = DatasetDict({
    'train': train,
    'validation': dev,
    'test': test
})
# dataset.save_to_disk("naijavoices_igbo_500h")

Sample duration: 500.05 hours
Manifest saved to ../naijavoices/igbo_train_manifest_500h.jsonl

In [42]:
train = sample_dataset(train_df, 250 * 60, "train_manifest", random_state=13)

# save to disk
dataset = DatasetDict({
    'train': train,
    'validation': dev,
    'test': test
})
# dataset.save_to_disk("naijavoices_igbo_250h")

Sample duration: 250.01 hours
Manifest saved to ../naijavoices/igbo_train_manifest_250h.jsonl

In [43]:
train = sample_dataset(train_df, 100 * 60, "train_manifest", random_state=16)

# save to disk
dataset = DatasetDict({
    'train': train,
    'validation': dev,
    'test': test
})
# dataset.save_to_disk("naijavoices_igbo_100h")

Sample duration: 100.00 hours
Manifest saved to ../naijavoices/igbo_train_manifest_100h.jsonl

In [44]:
train = sample_dataset(train_df, 1 * 60, "train_manifest", random_state=7)

# save to disk
dataset = DatasetDict({
    'train': train,
    'validation': dev,
    'test': test
})
dataset.save_to_disk("naijavoices_igbo_1h")

Sample duration: 1.00 hours
Manifest saved to ../naijavoices/igbo_train_manifest_1h.jsonl

Saving the dataset (0/1 shards):   0%|          | 0/927 [00:00<?, ? examples/s]

Saving the dataset (1/1 shards): 100%|██████████| 927/927 [00:00<00:00, 3272.53 examples/s]
Saving the dataset (1/1 shards): 100%|██████████| 927/927 [00:00<00:00, 4311.34 examples/s]
Saving the dataset (1/1 shards): 100%|██████████| 1014/1014 [00:00<00:00, 3755.89 examples/s]

In [45]:
train = sample_dataset(train_df, 1, "train_manifest", random_state=5)

# save to disk
dataset = DatasetDict({
    'train': train,
    'validation': dev,
    'test': test
})
dataset.save_to_disk("naijavoices_igbo_1m")

Sample duration: 1.00 minutes
Manifest saved to ../naijavoices/igbo_train_manifest_0h.jsonl

Saving the dataset (1/1 shards): 100%|██████████| 15/15 [00:00<00:00, 2132.62 examples/s]
Saving the dataset (0/1 shards):   0%|          | 0/927 [00:00<?, ? examples/s]

Saving the dataset (1/1 shards): 100%|██████████| 927/927 [00:00<00:00, 4820.55 examples/s]
Saving the dataset (1/1 shards): 100%|██████████| 1014/1014 [00:00<00:00, 4755.27 examples/s]

In [46]:
from IPython.display import Audio as DisplayAudio
import random

def display_audio_sample(dataset, index):
    """
    Display an audio sample from the dataset.
    """
    audio = dataset[index]['audio']
    text = dataset[index]['text']
    print(f"Text: {text}")
    print(f"Duration: {dataset[index]['duration']} seconds")
    print(f"Sampling rate: {audio['sampling_rate']} Hz")
    return DisplayAudio(audio['array'], rate=audio['sampling_rate'])

In [47]:
display_audio_sample(train, random.randint(0, len(train) - 1))

Text: ụmụaka ahụ ga-aga zụta bọọlụ ha ga-agba
Duration: 3.54 seconds
Sampling rate: 16000 Hz