# Imports

In [1]:
import os
import pandas as pd
from collections import Counter

# Prepare NaijaVoices dataset

In [2]:
train_path = "../naijavoices/train.csv"
dev_path = "../naijavoices/dev.csv"
test_path = "../naijavoices/test.csv"

train_df = pd.read_csv(train_path)
dev_df = pd.read_csv(dev_path)
test_df = pd.read_csv(test_path)

In [3]:
# get Yoruba subset
train_df = train_df[train_df['language'] == 'yoruba']
dev_df = dev_df[dev_df['language'] == 'yoruba']
test_df = test_df[test_df['language'] == 'yoruba']

# drop language column
train_df = train_df.drop(columns=['language'])
dev_df = dev_df.drop(columns=['language'])
test_df = test_df.drop(columns=['language'])

In [4]:
train_df.describe(include="all")

,speaker_id,audio,text,age_bracket,gender,phase,exists,duration,snr
count,666164,666164,666164,666164,666164,666164,666164.0,666126.000000,666118.000000
unique,1758,611830,211670,3,2,2,NaN,NaN,NaN
top,LRMKP,20240113151400-131-1453-241614-mo-ti-ologbo-to...,Àwọn ọ̀rẹ́ kan sọ ara wọn di olofoofo àwọn gba...,18-29,female,phase 1,NaN,NaN,NaN
freq,15326,100,132,403640,408964,463903,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.537338,80.851410
std,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.702836,28.526717
min,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.060000,-20.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.460000,53.199477
50%,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.180000,100.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,1.0,4.260000,100.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,1.0,67.200000,100.000000

In [5]:
dev_df.describe(include="all")

,speaker_id,audio,text,age_bracket,gender,phase,exists,duration,snr
count,1003,1003,1003,1003,1003,1003,1003.0,1003.000000,1003.000000
unique,571,1001,1000,3,2,2,NaN,NaN,NaN
top,L88Q7,20240113155851-131-1453-241668-arts-ti-wa-laay...,Arts ti wa laaye fun igba pipẹ,18-29,female,phase 1,NaN,NaN,NaN
freq,17,2,2,608,617,693,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.532881,81.652656
std,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.670113,28.623126
min,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.060000,11.835817
25%,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.400000,54.336665
50%,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.180000,100.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,1.0,4.290000,100.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,1.0,13.140000,100.000000

In [6]:
test_df.describe(include="all")

,speaker_id,audio,text,age_bracket,gender,phase,exists,duration,snr
count,1159,1159,1159,1159,1159,1159,1159.0,1159.000000,1159.000000
unique,574,1157,1149,3,2,2,NaN,NaN,NaN
top,FE6OQ,20240112082311-58-1023-234270-baba-mi-tun-e-ro...,ààrẹ bá gbó gbó orile-ede sòrò.,18-29,female,phase 1,NaN,NaN,NaN
freq,32,2,2,701,763,849,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.623244,79.832326
std,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.738963,29.311107
min,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.060000,6.420073
25%,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.460000,50.114714
50%,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.240000,100.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,1.0,4.380000,100.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,1.0,16.140000,100.000000

In [7]:
# check for missing values
train_df.isnull().sum()

speaker_id      0
audio           0
text            0
age_bracket     0
gender          0
phase           0
exists          0
duration       38
snr            46
dtype: int64

In [8]:
# drop rows with missing values in 'duration' column
train_df = train_df.dropna(subset=['duration'])

In [9]:
dev_df.isnull().sum()

speaker_id     0
audio          0
text           0
age_bracket    0
gender         0
phase          0
exists         0
duration       0
snr            0
dtype: int64

In [10]:
test_df.isnull().sum()

speaker_id     0
audio          0
text           0
age_bracket    0
gender         0
phase          0
exists         0
duration       0
snr            0
dtype: int64

In [11]:
# drop unnecessary columns
drop_cols = ['phase', 'exists', 'snr', 'speaker_id']
train_df.drop(columns=drop_cols + ['gender', 'age_bracket'], inplace=True)
dev_df.drop(columns=drop_cols + ['gender', 'age_bracket'], inplace=True)
test_df.drop(columns=drop_cols, inplace=True)

In [12]:
# find duplicates
train_df[train_df.duplicated(subset='audio')].sort_values(by='audio').head(10)

,audio,text,duration
813488,20231227200748-70-519-204268-w-n-ma-ti-adminis...,Wọ́n máa ti administrétíf blọọ̀kì táwọn Olùkọ́...,5.16
2074705,20231227200748-70-519-204268-w-n-ma-ti-adminis...,Wọ́n máa ti administrétíf blọọ̀kì táwọn Olùkọ́...,5.16
1416521,20231227200748-70-519-204268-w-n-ma-ti-adminis...,Wọ́n máa ti administrétíf blọọ̀kì táwọn Olùkọ́...,5.16
1611045,20231227202137-70-519-204289-dptm-nt-bayok-msr...,Dìpátímẹ̀ntì bayokẹ́mísìrì máa ń da ìmọ̀ bàyọ́...,5.94
1761492,20231227202137-70-519-204289-dptm-nt-bayok-msr...,Dìpátímẹ̀ntì bayokẹ́mísìrì máa ń da ìmọ̀ bàyọ́...,5.94
984188,20231227202137-70-519-204289-dptm-nt-bayok-msr...,Dìpátímẹ̀ntì bayokẹ́mísìrì máa ń da ìmọ̀ bàyọ́...,5.94
1655134,20231227203438-70-519-204309-jd-l-s-fak-t--k--...,Jídé lọ sí fakọ́tì ẹ̀kọ́ ọ̀gbìn lánàá,3.54
145253,20231227203438-70-519-204309-jd-l-s-fak-t--k--...,Jídé lọ sí fakọ́tì ẹ̀kọ́ ọ̀gbìn lánàá,3.54
2058146,20231227203438-70-519-204309-jd-l-s-fak-t--k--...,Jídé lọ sí fakọ́tì ẹ̀kọ́ ọ̀gbìn lánàá,3.54
1410750,20231227203438-70-519-204309-jd-l-s-fak-t--k--...,Jídé lọ sí fakọ́tì ẹ̀kọ́ ọ̀gbìn lánàá,3.54

In [13]:
dev_df[dev_df.duplicated(subset='audio')].sort_values(by='audio')

,audio,text,duration
2514,20240112130945-130-1462-381499-o-ye-ki-omo-ile...,O yẹ ki ọmọ ilẹ ìwé kàwé dáadáa.,2.04
2825,20240113155851-131-1453-241668-arts-ti-wa-laay...,Arts ti wa laaye fun igba pipẹ,2.34

In [14]:
test_df[test_df.duplicated(subset='audio')].sort_values(by='audio')

,audio,text,age_bracket,gender,duration
3043,20240112082311-58-1023-234270-baba-mi-tun-e-ro...,Bàbá mi tún ẹ̀rọ omi ilé ìwẹ̀ wa tí ó bájẹ̀ ṣe,18-29,female,4.08
2551,20240112102629-130-1464-381887-akunle-kan-fi-e...,Akunlé kan fi ẹnu ìkunlé rẹ̀ bọ ọ̀dà náà.,30-over,male,3.24

In [15]:
# drop duplicates
train_df = train_df.drop_duplicates(subset='audio')
dev_df = dev_df.drop_duplicates(subset='audio')
test_df = test_df.drop_duplicates(subset='audio')

In [16]:
# get the audio file paths
path = '../naijavoices/'

train_df['audio_filepath'] = train_df['audio'].apply(lambda x: os.path.join(os.path.dirname(path), "audio-unconverted", x))
dev_df['audio_filepath'] = dev_df['audio'].apply(lambda x: os.path.join(os.path.dirname(path), "audio-unconverted", x))
test_df['audio_filepath'] = test_df['audio'].apply(lambda x: os.path.join(os.path.dirname(path), "audio-unconverted", x))

# drop the `audio` column
train_df.drop(columns=['audio'], inplace=True)
dev_df.drop(columns=['audio'], inplace=True)
test_df.drop(columns=['audio'], inplace=True)

In [17]:
train_df.describe(include="all")

,text,duration,audio_filepath
count,611792,611792.000000,611792
unique,211660,NaN,611792
top,"Rárá, mi ò mọ̀.",NaN,../naijavoices/audio-unconverted/2024032117060...
freq,18,NaN,1
mean,NaN,3.559698,NaN
std,NaN,1.703722,NaN
min,NaN,0.060000,NaN
25%,NaN,2.460000,NaN
50%,NaN,3.240000,NaN
75%,NaN,4.320000,NaN
max,NaN,67.200000,NaN

In [18]:
dev_df.describe(include="all")

,text,duration,audio_filepath
count,1001,1001.000000,1001
unique,1000,NaN,1001
top,"Yo sọ pé ""Pe ẹniti ó ń tún ọkọ̀ se""",NaN,../naijavoices/audio-unconverted/2024030410163...
freq,2,NaN,1
mean,NaN,3.535564,NaN
std,NaN,1.670688,NaN
min,NaN,0.060000,NaN
25%,NaN,2.400000,NaN
50%,NaN,3.180000,NaN
75%,NaN,4.320000,NaN
max,NaN,13.140000,NaN

In [19]:
test_df.describe(include="all")

,text,age_bracket,gender,duration,audio_filepath
count,1157,1157,1157,1157.000000,1157
unique,1149,3,2,NaN,1157
top,Arabinrin atijọ naa yoo ṣe itọsọna wa awọn ipa...,18-29,female,NaN,../naijavoices/audio-unconverted/2024032308323...
freq,2,700,762,NaN,1
mean,NaN,NaN,NaN,3.623181,NaN
std,NaN,NaN,NaN,1.740378,NaN
min,NaN,NaN,NaN,0.060000,NaN
25%,NaN,NaN,NaN,2.460000,NaN
50%,NaN,NaN,NaN,3.240000,NaN
75%,NaN,NaN,NaN,4.380000,NaN
max,NaN,NaN,NaN,16.140000,NaN

In [20]:
# remove long audio files from train and dev sets
train_df = train_df[train_df['duration'] <= 15]
dev_df = dev_df[dev_df['duration'] <= 15]
print(f"Total training set duration: {train_df['duration'].sum() / 3600:.2f} hours")

Total training set duration: 603.28 hours

In [21]:
train_df.head()

,text,duration,audio_filepath
1,Mo wà ilẹ̀ oní yàrà ibusun mẹta.,2.82,../naijavoices/audio-unconverted/2024032223305...
2,Bẹ́ẹ̀ni ara àbùdá snapchat ni ìfiránṣẹ́ tó ń f...,6.84,../naijavoices/audio-unconverted/2024012414432...
9,Àwọn owó ẹyọ ni wọn máa lò níbi ètò mímú wọ ẹg...,3.60,../naijavoices/audio-unconverted/2024030822582...
10,A lè rí ẹ̀sọ́ ara láti ara irin,1.80,../naijavoices/audio-unconverted/2024012112424...
13,Dele yóò tún ilé gbé latí ibùgbé tálákà lọ sí ...,4.26,../naijavoices/audio-unconverted/2024022216224...

In [22]:
# save original text before cleaning
train_df['original_text'] = train_df['text']
dev_df['original_text'] = dev_df['text']
test_df['original_text'] = test_df['text']

In [23]:
# lowercase the text
train_df['text'] = train_df['text'].str.lower()
dev_df['text'] = dev_df['text'].str.lower()
test_df['text'] = test_df['text'].str.lower()

# get the set of characters in the text
train_text = "".join(train_df['text'].tolist())
dev_text = "".join(dev_df['text'].tolist())
text = train_text + dev_text

set(text)

{'\t',
 ' ',
 '!',
 '"',
 '#',
 '$',
 '%',
 '&',
 "'",
 '(',
 ')',
 '*',
 '+',
 ',',
 '-',
 '.',
 '/',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '=',
 '?',
 '[',
 '\\',
 ']',
 '_',
 '`',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '|',
 '\xa0',
 '´',
 '¸',
 'à',
 'á',
 'â',
 'ã',
 'ä',
 'å',
 'ç',
 'è',
 'é',
 'ê',
 'ë',
 'ì',
 'í',
 'î',
 'ï',
 'ð',
 'ñ',
 'ò',
 'ó',
 'ô',
 'õ',
 'ö',
 '÷',
 'ù',
 'ú',
 'û',
 'ü',
 'ý',
 'ÿ',
 'ā',
 'ē',
 'ė',
 'ę',
 'ě',
 'ī',
 'ĭ',
 'ı',
 'ń',
 'ŋ',
 'ō',
 'œ',
 'ś',
 'ş',
 'š',
 'ũ',
 'ū',
 'ƒ',
 'ǵ',
 'ǹ',
 'ș',
 'ɛ',
 'ɡ',
 '̀',
 '́',
 '̂',
 '̃',
 '̄',
 '̇',
 '̈',
 '̌',
 '̣',
 '̧',
 '̩',
 '̵',
 '̀',
 '́',
 'ḍ',
 'ḥ',
 'ḳ',
 'ḿ',
 'ṅ',
 'ṛ',
 'ṣ',
 'ṭ',
 'ạ',
 'ẹ',
 'ẽ',
 'ị',
 'ọ',
 'ụ',
 '\u200b',
 '\u200c',
 '–',
 '‘',
 '’',
 '“',
 '”',
 '…'}

In [24]:
char = '\u200c'

# find rows with the character
train_df[train_df['text'].str.contains(char)]

,text,duration,audio_filepath,original_text
730927,"ibi gbogbo là ńdá iná alẹ‌, ọbẹ‌ ló kàn dùn ju...",3.60,../naijavoices/audio-unconverted/2024031921334...,"Ibi gbogbo là ńdá iná alẹ‌, ọbẹ‌ ló kàn dùn ju..."
1124132,"ibi gbogbo là ńdá iná alẹ‌, ọbẹ‌ ló kàn dùn ju...",5.82,../naijavoices/audio-unconverted/2024021918373...,"Ibi gbogbo là ńdá iná alẹ‌, ọbẹ‌ ló kàn dùn ju..."
2064629,"ibi gbogbo là ńdá iná alẹ‌, ọbẹ‌ ló kàn dùn ju...",5.70,../naijavoices/audio-unconverted/2024022118351...,"Ibi gbogbo là ńdá iná alẹ‌, ọbẹ‌ ló kàn dùn ju..."

In [25]:
print(f"'{char}'")

'‌'

In [26]:
# remove punctuation and special characters
CHARS_TO_REMOVE = ['"', '!', 'ǃ', '(', ')', ',', '.', ':', ';', '?', '[', ']', '\u200b', '\u200c', '“', '”']

for char in CHARS_TO_REMOVE:
    train_df['text'] = train_df['text'].str.replace(char, '', regex=False)
    dev_df['text'] = dev_df['text'].str.replace(char, '', regex=False)
    test_df['text'] = test_df['text'].str.replace(char, '', regex=False)

# replace whitespace characters with a single space
WHITESPACE_CHARS = ['\xa0', '\t', '/']
for char in WHITESPACE_CHARS:
    train_df['text'] = train_df['text'].str.replace(char, ' ', regex=False)
    dev_df['text'] = dev_df['text'].str.replace(char, ' ', regex=False)
    test_df['text'] = test_df['text'].str.replace(char, ' ', regex=False)

# strip leading and trailing whitespace from the text column
train_df['text'] = train_df['text'].str.strip()
dev_df['text'] = dev_df['text'].str.strip()
test_df['text'] = test_df['text'].str.strip()

# remove excess whitespace
train_df['text'] = train_df['text'].str.replace(r'\s+', ' ', regex=True)
dev_df['text'] = dev_df['text'].str.replace(r'\s+', ' ', regex=True)
test_df['text'] = test_df['text'].str.replace(r'\s+', ' ', regex=True)

In [27]:
# get the frequency of each character in the train and dev sets
char_freq = Counter(text)
char_freq

Counter({' ': 4774553,
         'n': 1773449,
         'i': 1247457,
         'ọ': 1176437,
         'a': 1164234,
         'l': 769631,
         '́': 765889,
         'à': 764186,
         'o': 740928,
         'ẹ': 726254,
         'r': 698843,
         '̀': 695056,
         'í': 694229,
         'á': 662915,
         'b': 651717,
         't': 599402,
         'w': 578250,
         'k': 541432,
         'm': 511394,
         'ì': 483336,
         'e': 407861,
         'g': 389149,
         's': 364521,
         'j': 360485,
         'ó': 349851,
         'd': 328275,
         'ú': 325651,
         'y': 320686,
         'é': 316617,
         'u': 311400,
         'ò': 296161,
         'p': 273960,
         'f': 268320,
         'ṣ': 257263,
         '.': 250756,
         'è': 171339,
         'ù': 148793,
         'ń': 100290,
         ',': 73490,
         '?': 71099,
         '-': 64108,
         '̣': 59483,
         'h': 50089,
         '̩': 28471,
         '!': 19518,
         'c': 19407,
         'ǹ': 15171,
         '́': 11162,
         '"': 8079,
         '̀': 7506,
         "'": 5157,
         'v': 3996,
         'z': 2931,
         '2': 1279,
         'x': 1208,
         '1': 1082,
         '“': 1062,
         '0': 1018,
         '”': 996,
         '9': 806,
         'q': 713,
         ';': 459,
         'õ': 409,
         'ã': 400,
         '\xa0': 384,
         '4': 367,
         '8': 352,
         '3': 343,
         '’': 327,
         '5': 290,
         '/': 290,
         '6': 269,
         'ī': 257,
         'ạ': 241,
         '7': 235,
         'â': 176,
         ':': 170,
         ')': 167,
         '(': 162,
         '\u200b': 154,
         '‘': 133,
         'ë': 120,
         'ḿ': 116,
         'ę': 109,
         'ô': 101,
         '̄': 97,
         'š': 87,
         '̇': 84,
         'å': 80,
         'ụ': 69,
         'ñ': 62,
         'ị': 60,
         'î': 58,
         'ê': 46,
         'ḍ': 46,
         'ö': 43,
         'ș': 42,
         'ė': 37,
         'ı': 33,
         'ş': 30,
         '+': 30,
         'ē': 29,
         'ō': 28,
         '÷': 25,
         'ï': 25,
         '̂': 24,
         'ü': 21,
         'ÿ': 20,
         'ä': 19,
         '̃': 18,
         'ū': 16,
         '&': 15,
         '\t': 13,
         'û': 13,
         'ā': 12,
         'ũ': 12,
         'ý': 11,
         '¸': 11,
         'ĭ': 10,
         'ṅ': 10,
         'ḳ': 10,
         '|': 9,
         'ḥ': 9,
         'ƒ': 8,
         'ě': 8,
         '*': 8,
         '#': 8,
         'ǵ': 7,
         'ṭ': 6,
         'ç': 6,
         'ð': 6,
         '`': 6,
         '_': 6,
         '…': 6,
         'ɡ': 6,
         '\\': 6,
         '–': 6,
         '\u200c': 6,
         '̌': 5,
         'ẽ': 4,
         'ś': 4,
         '̧': 4,
         '=': 3,
         '%': 3,
         '[': 3,
         ']': 3,
         '´': 3,
         'ɛ': 3,
         'ŋ': 3,
         'ṛ': 3,
         '$': 3,
         'œ': 2,
         '̈': 2,
         '̵': 2})

In [28]:
# remove rows with infrequent characters from train and dev sets
min_freq = 235
train_df = train_df[train_df['text'].apply(lambda x: all(char_freq[c] >= min_freq for c in x))]
dev_df = dev_df[dev_df['text'].apply(lambda x: all(char_freq[c] >= min_freq for c in x))]

In [29]:
# recalculate character frequency after cleaning
train_text = "".join(train_df['text'].tolist())
dev_text = "".join(dev_df['text'].tolist())
text = train_text + dev_text

# get the frequency of each character in the train and dev sets
char_freq = Counter(text)
char_freq

Counter({' ': 4751646,
         'n': 1767829,
         'i': 1242762,
         'ọ': 1173827,
         'a': 1160468,
         'l': 767191,
         '́': 763654,
         'à': 762243,
         'o': 738311,
         'ẹ': 724629,
         'r': 696582,
         '̀': 692752,
         'í': 692436,
         'á': 660956,
         'b': 649778,
         't': 597450,
         'w': 576470,
         'k': 539658,
         'm': 510079,
         'ì': 482289,
         'e': 406270,
         'g': 387955,
         's': 363311,
         'j': 359360,
         'ó': 348813,
         'd': 327276,
         'ú': 324811,
         'y': 319762,
         'é': 315784,
         'u': 310254,
         'ò': 294860,
         'p': 273043,
         'f': 267422,
         'ṣ': 256545,
         'è': 170522,
         'ù': 148434,
         'ń': 100126,
         '-': 63903,
         '̣': 59308,
         'h': 49865,
         '̩': 27980,
         'c': 19311,
         'ǹ': 15113,
         '́': 11162,
         '̀': 7506,
         "'": 5144,
         'v': 3981,
         'z': 2919,
         '2': 1273,
         'x': 1202,
         '1': 1071,
         '0': 985,
         '9': 798,
         'q': 709,
         'ã': 383,
         '4': 363,
         '8': 352,
         '3': 343,
         'õ': 339,
         '5': 280,
         '6': 269,
         'ī': 253,
         'ạ': 241,
         '7': 235,
         '’': 203})

In [30]:
# remove rows with anomalous character rates
train_df['character_rate'] = train_df['text'].str.len() / train_df['duration']
train_df['character_rate'].describe()

count    609728.000000
mean         15.335265
std          34.107728
min           1.418440
25%           9.929078
50%          11.607143
75%          13.480392
max        1750.000000
Name: character_rate, dtype: float64

In [31]:
dev_df['character_rate'] = dev_df['text'].str.len() / dev_df['duration']
dev_df['character_rate'].describe()

count    997.000000
mean      14.684192
std       29.044726
min        2.446483
25%       10.087719
50%       11.711712
75%       13.565891
max      716.666667
Name: character_rate, dtype: float64

In [32]:
MAX = 25
train_df = train_df[train_df['character_rate'] <= MAX]
dev_df = dev_df[dev_df['character_rate'] <= MAX]

train_df.drop(columns=['character_rate'], inplace=True)
dev_df.drop(columns=['character_rate'], inplace=True)

In [33]:
# save to NeMo jsonl format
train_manifest_path = os.path.join(os.path.dirname(path), "yoruba_train_manifest.jsonl")
dev_manifest_path = os.path.join(os.path.dirname(path), "yoruba_dev_manifest.jsonl")
test_manifest_path = os.path.join(os.path.dirname(path), "yoruba_test_manifest.jsonl")

train_df.to_json(train_manifest_path, orient='records', lines=True)
dev_df.to_json(dev_manifest_path, orient='records', lines=True)
test_df.to_json(test_manifest_path, orient='records', lines=True)
print(f"Manifests saved to {path}")

Manifests saved to ../naijavoices/

# Sample

In [34]:
# get the total duration of each split
train_duration = train_df['duration'].sum()
dev_duration = dev_df['duration'].sum()
test_duration = test_df['duration'].sum()
print(f"Train duration: {train_duration / 3600:.2f} hours")
print(f"Dev duration: {dev_duration / 3600:.2f} hours")
print(f"Test duration: {test_duration / 3600:.2f} hours")

Train duration: 600.35 hours
Dev duration: 0.98 hours
Test duration: 1.16 hours

In [35]:
# rename the 'audio_filepath' column to 'audio'
train_df = train_df.rename(columns={'audio_filepath': 'audio'})
dev_df = dev_df.rename(columns={'audio_filepath': 'audio'})
test_df = test_df.rename(columns={'audio_filepath': 'audio'})

In [36]:
from datasets import Dataset, DatasetDict, Audio

dev = Dataset.from_pandas(dev_df)
test = Dataset.from_pandas(test_df)

/mnt/volume/workdir/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [37]:
# only keep necessary columns
cols = ['audio', 'text', 'duration']
dev = dev.remove_columns([col for col in dev.column_names if col not in cols])
test = test.remove_columns([col for col in test.column_names if col not in cols + ['gender', 'age_bracket']])

In [38]:
# cast audio column to Audio type
dev = dev.cast_column("audio", Audio(16000))
test = test.cast_column("audio", Audio(16000))

In [39]:
test[0]

{'text': 'ọmọ ọ̀jọ̀gbọ́n fẹ̀yìntì ni mò ń fẹ́',
 'age_bracket': '18-29',
 'gender': 'female',
 'duration': 2.28,
 'audio': <datasets.features._torchcodec.AudioDecoder at 0x7d8b0f284230>}

In [40]:
def sample_dataset(df, duration_minutes, manifest_name, random_state=1):
    """
    Sample a dataset to a specific duration.
    """
    total_duration = float(df['duration'].sum())
    ratio = (duration_minutes * 60) / total_duration
    n = int(len(df) * ratio)
    sample = df.sample(n=n, random_state=random_state)
    sample = sample.sample(frac=1, random_state=random_state).reset_index(drop=True)
    sample_duration = sample['duration'].sum()
    if sample_duration >= 3600:
        print(f"Sample duration: {sample_duration / 3600:.2f} hours")
    else:
        print(f"Sample duration: {sample_duration / 60:.2f} minutes")

    # save to new manifest
    sample_manifest_path = os.path.join(
        os.path.dirname(path),
        f"yoruba_{manifest_name}_{int(sample_duration / 3600)}h.jsonl"
    )
    sample.to_json(sample_manifest_path, orient="records", lines=True)
    print(f"Manifest saved to {sample_manifest_path}")

    dataset = Dataset.from_pandas(sample)
    dataset = dataset.remove_columns([col for col in dataset.column_names if col not in cols])
    dataset = dataset.cast_column("audio", Audio(16000))
    return dataset

In [41]:
train = sample_dataset(train_df, 500 * 60, "train_manifest", random_state=3)

# save to disk
dataset = DatasetDict({
    'train': train,
    'validation': dev,
    'test': test
})
# dataset.save_to_disk("naijavoices_yoruba_500h")

Sample duration: 500.02 hours
Manifest saved to ../naijavoices/yoruba_train_manifest_500h.jsonl

In [42]:
train = sample_dataset(train_df, 250 * 60, "train_manifest", random_state=2)

# save to disk
dataset = DatasetDict({
    'train': train,
    'validation': dev,
    'test': test
})
# dataset.save_to_disk("naijavoices_yoruba_250h")

Sample duration: 250.00 hours
Manifest saved to ../naijavoices/yoruba_train_manifest_249h.jsonl

In [43]:
train = sample_dataset(train_df, 100 * 60, "train_manifest", random_state=16)

# save to disk
dataset = DatasetDict({
    'train': train,
    'validation': dev,
    'test': test
})
# dataset.save_to_disk("naijavoices_yoruba_100h")

Sample duration: 100.01 hours
Manifest saved to ../naijavoices/yoruba_train_manifest_100h.jsonl

In [44]:
train = sample_dataset(train_df, 1 * 60, "train_manifest", random_state=4)

# save to disk
dataset = DatasetDict({
    'train': train,
    'validation': dev,
    'test': test
})
# dataset.save_to_disk("naijavoices_yoruba_1h")

Sample duration: 1.00 hours
Manifest saved to ../naijavoices/yoruba_train_manifest_1h.jsonl

In [45]:
train = sample_dataset(train_df, 1, "train_manifest", random_state=12)

# save to disk
dataset = DatasetDict({
    'train': train,
    'validation': dev,
    'test': test
})
dataset.save_to_disk("naijavoices_yoruba_1m")

Sample duration: 1.01 minutes
Manifest saved to ../naijavoices/yoruba_train_manifest_0h.jsonl

Saving the dataset (1/1 shards): 100%|██████████| 16/16 [00:00<00:00, 1113.42 examples/s]
Saving the dataset (0/1 shards):   0%|          | 0/983 [00:00<?, ? examples/s]

Saving the dataset (1/1 shards): 100%|██████████| 983/983 [00:01<00:00, 802.46 examples/s]
Saving the dataset (1/1 shards): 100%|██████████| 1157/1157 [00:01<00:00, 836.29 examples/s]

In [46]:
from IPython.display import Audio as DisplayAudio
import random

def display_audio_sample(dataset, index):
    """
    Display an audio sample from the dataset.
    """
    audio = dataset[index]['audio']
    text = dataset[index]['text']
    print(f"Text: {text}")
    print(f"Duration: {dataset[index]['duration']} seconds")
    print(f"Sampling rate: {audio['sampling_rate']} Hz")
    return DisplayAudio(audio['array'], rate=audio['sampling_rate'])

In [47]:
display_audio_sample(train, random.randint(0, len(train) - 1))

Text: mó tí gbọ́ nípa àṣa gbígbé papọ̀ láì tíì ṣe ìgbéyàwó
Duration: 4.26 seconds
Sampling rate: 16000 Hz